### ISSUE TITLE
Renew HpS

### ISSUE THREAD

**Issue by Flowy** [oskarholmberg/wow-downranking#22]
Hi, looking on HpS table for renew and that does not make sense.
Case:
Duration: 15s
Ticks every 3s
Ticks for 190hp
total ticks is 5
total healed hp 950 (that is correct)
But shows hps 190 (3x more than real, may be in case if you apply on 3 targets, but then mana is different)

Can you please check that?

**Comment by oskarwiskman** [comment]
Thanks for the feedback, will have a look at it.

**Comment by oskarwiskman** [comment]
Issue has been resolved. The hps for HoTs should now be calculated correctly.
