### ISSUE TITLE
Paladin Blessing of Light

### ISSUE THREAD

**Issue by KartonArmadon** [oskarholmberg/wow-downranking#23]
Paladin's Flash Light and Holy Light does not affected by Blessing of Light

**Comment by oskarwiskman** [comment]
I have not included that type of buffs yet, since there are so many external buffs you can apply to a target or yourself to increase your healing done. Blessing of Light might be a good candidate for an exception, and I will look in to adding it, but no promises.

**Comment by oskarwiskman** [comment]
Support for buffs has now been added, only Blessing of Light implemented as of now.
