### ISSUE TITLE
Druid Healing Touch costCoeff discrepancy in calculations.js

### ISSUE THREAD

**Issue by davidw3** [oskarholmberg/wow-downranking#27]
Hey on lines 182 and 190 in calculations.js, you compute your costCoeff as the product of all mana cost reduction coefficients. This needs to be ADDITIVE, i.e costCoeff = (1-0.09-0.1) for 3/3 moonglow & 5/5 tranquil spirit, not (1-0.09)*(1-0.1) as currently computed. This was discovered specifically when finding out healing touch rank 10 with 3/3 moonglow and 5/5 tranquil spirit costs 583 mana, instead of 589 mana in game. Its only a small difference, but I thought you might care.

**Comment by oskarwiskman** [comment]
Thanks for finding this. Fix is in.
