### ISSUE TITLE
Support for Chain Heal bounces

### ISSUE THREAD

**Issue by NGuldager** [oskarholmberg/wow-downranking#29]
Any plan to add support for the bounces of Chain Heal.

While the current tool is really good, it doesn't really show the full view for Chain Heal. Specifically if you also want to take into account the 3/8 tier 2, and/or 5/5 tier 2.5, which can decide if a lower amount of +heal will outperform a higher +heal in specific scenarios.

Depending on the implementation this could also add support for 8/8 tier 1 for shamans and Healing Wave

**Comment by oskarwiskman** [comment]
Hello, thanks for the feedback. I have considered adding some sort of scaling for chain heal (since I main a Shaman myself). I don't have anything in the pipeline as of now, but will leave this issue open as a reminder.

**Comment by oskarwiskman** [comment]
Glad to inform you that this has been added as of august 2021. Hope you still get any use out of it!
