### ISSUE TITLE
https://www.wowdownrank.com down

### ISSUE THREAD

**Issue by Zebouski** [oskarholmberg/wow-downranking#37]
Not sure how else to contact you, but ya website is down, was trying to link someone to it today :(

**Comment by oskarwiskman** [comment]
Yeah, I stopped maintaining it after WotlK released and shortly after that also dropped domain and server fees since traffic was so low. I was meaning to rewrite it to a single page html file that can just be run in a browser but never got to it.

**Comment by Zebouski** [comment]
Understandable thats what I assumed. We vanilla and tbc enjoyers miss the tool still theres still not a better place to really show people how this stuff works.

I did a quick look through the code, is there any user input that the app was running through serverside? It looks to me like all the computation was client side, and so we could just literally by hand just save all the html files that `npm start` serves us and slap them into a dist/ folder that github pages would host for free. If you could confirm that yeah its all clientside then yeah I could do this for ya. I worked on another project that used gulp to build a dist to html like this and it worked great, I could try setting that up too but the tech setup is new to me.

**Comment by oskarwiskman** [comment]
There is no reason at all for it to run on a node server really. I wasnt sure on how I would end up serving things, and had plans to make a login system hooked up to WoW Armory and stuff but that never happened. Which means that this could all run on a github pages, I just havent had the energy to rewrite it. If you want to do it I will happily approve the PR, or if you prefer to fork it and host it yourself that is all fine by me. Only thing I ask is that you please keep it publicly available and without ads. 

PS. It is honestly very humbling that people still have an interest is this, so thanks a lot for being willing to pick this up!
