### ISSUE TITLE
Website down, need alternative for self host

### ISSUE THREAD

**Issue by catpokemon** [oskarholmberg/wow-downranking#38]
hello!
is anyone able to share how to self host the downranking tool in a browser or otherwise? way back machine doesn’t work for the website unfortunately.

**Comment by Etou11** [comment]
0. Download & install node.js (https://nodejs.org/en/download/)
1. Download the project as .ZIP (Code -> Download ZIP)
2. Extract the content of in a directory of your liking (f. i. D:\Extract\)
3. Navigate to the root directory (wow-downranking-master) in your file explorer
4. Copy the exact path to this folder (click inside the bar left of the search bar in Windows File Explorer). For instance "D:\Extract\wow-downranking-master"
5. Open Windows PowerShell (hit Windows-key and type Windows PowerShell)
6. In Windows PowerShell type: _cd <exact_path_to_root_directory>_    (For instance: _cd D:\Extract\wow-downranking-master_)
7. Type: _npm install_   (It will tell you that there are vulnerabilities. This is fine, ignore it.)
8. Type: _npm start_   (This will start the server. To terminate the server hit Ctrl + C.)
9. In your browser navigate to http://localhost:3000

**Comment by oskarwiskman** [comment]
Thanks for answering @Etou11 , I haven't been maintaining this repo since WotLK released and had stopped paying domain and server fees since traffic to the site basically died for obvious reasons.
